### ISSUE TITLE
插件主页图片和文字显示有问题

### ISSUE THREAD

**Issue by xiaomifan233** [PRO-2684/transitio#16]
![QQ截图20240203201828](https://github.com/PRO-2684/transitio/assets/113199948/7d2cb9eb-bdd2-47b4-8b56-b06db4f52e8e)
将窗口调节至最窄会有图标与文字会有部分重叠
给作者提一点小小的建议吧

**Comment by PRO-2684** [comment]
在我的电脑上最小是刚好不会重叠的，既然不怎么影响日常使用那就下个版本加点透明度好了
