### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by SoudayoWwww** [PRO-2684/transitio#20]
![1](https://github.com/PRO-2684/transitio/assets/52328223/b425516c-e4f5-46f6-81bf-b08778ce2054)
![2](https://github.com/PRO-2684/transitio/assets/52328223/71ef2dc7-1848-4d05-884d-c9a404026b60)
QQNT9.9.9更新之后群聊出现了名片，强制开启无法关闭，不知道作者有无意向开发一个隐藏名片颜色和LVxxx字段的CSS（类似于9.9.9版本之前的只有管理和群主有颜色，但是保留自定义头衔），如果因为精力问题或者担心qq本体更新频繁那就算了吧。

**Comment by PRO-2684** [comment]
可以参考 https://t.me/ntqqtweaks/23 修改
由于我没有更新 QQ，无法测试，若你测试成功的话欢迎 PR
