### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by YatFanLan** [PRO-2684/transitio#41]
能否加入群聊内的图片禁止下载功能。或者是提供一个关闭自动下载功能

**Comment by PRO-2684** [comment]
与此插件的定位不符，建议前往 [LiteLoaderQQNT/LiteLoaderQQNT](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 或 [xiyuesaves/LiteLoaderQQNT-lite_tools](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues) 提 FR
