### ISSUE TITLE
[BUG] 与 QQ 新版配色可能造成的冲突

### ISSUE THREAD

**Issue by orangeZSCB** [PRO-2684/transitio#44]
## 预览

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/03f916ef-182a-4d02-98aa-d053ba7c934a">

（前后，因为我有两个号）

## Bug 介绍

从 QQNT 老版本升级到 QQNT 新版本之后，配色不会自动改变至 QQ 最新版的死人配色，但是因为我<del>该死的好奇心</del>用了一小下 QQ 调色盘，用了之后重置了，才发现配色不是 Transitio 中加载的 css file 了

## 复现步骤

**注意：请谨慎复现 ~~，最好在虚拟机里~~**

1. 加载 Transitio，和最新版本 QQNT
2. 打开超级调色盘试用
3. 十分钟后自动重置，或者手动重置
4. 发现 css file 被顶掉，除了好友列表和 Setting

## 说点闲话

~~死人腾讯，连 ten-cent 都不值~~

**Comment by orangeZSCB** [comment]
否，包括重装 Transitio，重载 css file 均无效。~~重装 LLQQNT 没有试过~~

**Comment by PRO-2684** [comment]
可以在 devtools 内看到目标 css 吗

**Comment by orangeZSCB** [comment]
唔姆 还没去看过
我去看一眼

**Comment by orangeZSCB** [comment]
![image](https://github.com/user-attachments/assets/7362d0bb-f18b-4d06-8358-6529a4e7e378)
指向此 css
```HTML
<link rel="stylesheet" href="app://./renderer/css/40475.7d3f1ca5.css">
```

**Comment by orangeZSCB** [comment]
但是这个 css 删了之后就有大问题，按钮什么的都看不见

**Comment by orangeZSCB** [comment]
<img width="688" alt="image" src="https://github.com/user-attachments/assets/70bfb006-0993-4760-a324-abfce3b708cd">

**Comment by PRO-2684** [comment]
devtools 内注入的用户样式是有的吧，那可能是 qq 新的 css 优先级较高，可以尝试在用户样式内的相关地方添加 `!important`

**Comment by orangeZSCB** [comment]
是的（）
知道了（）

**Comment by orangeZSCB** [comment]
但是加上了 `!important` 之后，qq 的新 css 优先级还是很高（）

**Comment by PRO-2684** [comment]
那可以尝试多加几层选择器来增加优先级，如果这也不行那可能就没有很好的解决方案了，毕竟 transitio 的样式都是注入在最后的
