### ISSUE TITLE
新建议

### ISSUE THREAD

**Issue by YatFanLan** [PRO-2684/transitio#45]
你好  在我使用这个插件的时候，其中 [Sidebar-Managemen](https://github.com/PRO-2684/Transitio-user-css/?tab=readme-ov-file#customize-more-menu)t css文件  有隐藏设置中的 一些功能选项 请问能够在打开设置之前酒调用这个css文件吗？ 每回重新打开这个设置界面的时候 超级调色板会闪一下然后消失

**Comment by PRO-2684** [comment]
据我所知目前的实现已经是注入时机最早的了
