### ISSUE TITLE
[Bug] 与 LLOneBot 冲突

### ISSUE THREAD

**Issue by TransparentLC** [PRO-2684/transitio#52]
如题，在设置中无法展示已有的样式，点击“打开目录”没有反应，样式也不会在任何窗口产生效果。

已在只启用 Transitio 和 LLOneBot 并移除其他插件的情况下验证过，此时移除 LLOneBot 则 Transitio 可以正常使用。

版本：
QQ: 9.9.16-28971
LiteLoaderQQNT: 1.2.3
Transitio: 1.5.4
LLOneBot: 4.1.4

**Comment by PRO-2684** [comment]
此插件并未进行任何 hook 操作，而 llob 含有 hook 操作，因此冲突很有可能是它的问题，请先附上日志，让 llob 开发者调查一下

**Comment by TransparentLC** [comment]
LLOneBot 4.2.1 已修复
