### ISSUE TITLE
恢复默认功能

### ISSUE THREAD

**Issue by TWHking** [PRO-2684/transitio#53]
建议加个每个选项的恢复默认功能,有时候调整颜色歪了但是又忘了之前的具体色值了挺麻烦的

**Comment by PRO-2684** [comment]
将鼠标悬浮在输入框即可看到默认值的提示

**Comment by PRO-2684** [comment]
如果要重置整个样式的设置，可以右击齿轮图标

**Comment by TWHking** [comment]
> 将鼠标悬浮在输入框即可看到默认值的提示

好的了解
