### ISSUE TITLE
建议数据文件夹里的样式可以递归读取

### ISSUE THREAD

**Issue by lamprose** [PRO-2684/transitio#6]
数据文件夹`plugins_data/transitio/styles/`里的样式可以递归读取，也就是可以在这个文件夹里创建文件夹然后在放置css样式文件依然可以生效，且只加载css文件

**Comment by PRO-2684** [comment]
做是可以做，但是实际应用场景好像不是很明显，除非设置界面同步做个文件夹分类 🤔

**Comment by lamprose** [comment]
你把css单独提出来了 这不就是使用场景吗  我把css仓库克隆到`plugins_data/transitio/styles/`  更新什么的不是更方便吗   不用每次都去复制粘贴

**Comment by PRO-2684** [comment]
由于 Transitio 的内部实现以及 chromium 的一些特性，目前没有找到很好的解决方案

具体来说，就是为了避免多个目录下的同名文件问题，势必要展示目录。Transitio 通过元素的 id 来区分注入的各个 css 文件，但是元素 id 中有 `/` 或 `\\` 等特殊字符时就会导致选择元素时有各类问题。如果不通过 id 中这些特殊字符来区分目录层级的话，还是会出现同名问题。

不过，可以做个文件软链接的支持，方便你开发 CSS。

**Comment by lamprose** [comment]
也用短横线连接文件夹和文件  反正你只需要通过id找到css就行  又不需要通过id反推css文件所在路径 最好是在id生成时写个校验得方法，一旦文件夹名或者文件名不合法就不加载且在界面设置上提示

**Comment by PRO-2684** [comment]
> 也用短横线连接文件夹和文件 反正你只需要通过id找到css就行 又不需要通过id反推css文件所在路径 最好是在id生成时写个校验得方法，一旦文件夹名或者文件名不合法就不加载且在界面设置上提示

有可能造成冲突，比如说 `abc/def.css` 和 `abc-def.css`

**Comment by PRO-2684** [comment]
现已支持
