### ISSUE TITLE
打开样式目录会报错；导入css文件，重启后，css列表依旧空白

### ISSUE THREAD

**Issue by Sunshagon** [PRO-2684/transitio#7]
Windows不到件
'C:\Users\Sunsh\Documents\LiteLoaderQQNT\plugins_data\transitio\styles'。请确定文件名是否正确后，再试一次。

**Comment by PRO-2684** [comment]
尝试手动创建一下这个文件夹？

**Comment by Sunshagon** [comment]
> 尝试手动创建一下这个文件夹？应该是在更新过程中不小心把自动创建文件夹的逻辑删掉了

可以手动创建，但是这个导入css，该怎么生效呢？

**Comment by PRO-2684** [comment]
目录创建好后重启应该就可以正常使用了
