### ISSUE TITLE
希望兼容伪元素支持

### ISSUE THREAD

**Issue by Huanting93** [PRO-2684/transitio#9]
一添加伪元素  页面某些按钮就点击不了  不知道哪里冲突了

**Comment by Huanting93** [comment]
比如这一段
div#qContextMenu::after,
.q-context-sub-menu__container::after {
    position: absolute;
    left: 0;
    right: 0;
    content: "";
    top: 0;
    bottom: -50px;
}

**Comment by PRO-2684** [comment]
此插件只是把用户的 CSS 添加到了 QQ 的界面里，这些 CSS 的问题我也无法解决

比如说给 context menu 加个 `backdrop-filter` 后，二级菜单位置就会有偏移，谁也不知道是怎么导致的
